/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Secretaria;

import clinicaMedica.Consulta.MenuConsultas;
import clinicaMedica.Consulta.PainelAtualizarConsulta;
import clinicaMedica.Consulta.PainelCadastrarConsulta;
import clinicaMedica.Consulta.PainelRelatorioConsulta;
import clinicaMedica.Consulta.PainelRemoverConsulta;
import clinicaMedica.Menu;
import clinicaMedica.Paciente.AtualizaPaciente;
import clinicaMedica.Paciente.CadastroPaciente;
import clinicaMedica.Paciente.RemovePaciente;

/**
 * Painel principal do módulo Secretária.
 * Gerencia a navegação entre telas de cadastro, atualização e remoção de pacientes,
 * bem como o gerenciamento de consultas.
 * Utiliza CardLayout para alternância entre diferentes painéis.
 * 
 * @author Joaquim
 */
public class PainelSecretaria extends javax.swing.JPanel {

    /** Painel de cadastro de consultas. */
    private PainelCadastrarConsulta cadastrarConsulta;
    
    /** Painel de atualização de consultas. */
    private PainelAtualizarConsulta atualizarConsulta;
    
    /** Painel de remoção de consultas. */
    private PainelRemoverConsulta removerConsulta;

    /**
     * Cria e inicializa o painel da secretária.
     * Configura o CardLayout e registra todos os painéis filhos.
     */
    public PainelSecretaria() {
        initComponents();
        
        setLayout(new java.awt.CardLayout());
        
        CadastroPaciente cadastro = new CadastroPaciente();
        AtualizaPaciente atualiza = new AtualizaPaciente();
        RemovePaciente remover = new RemovePaciente();
        Menu menu = new Menu();
        
        MenuConsultas menuConsultas = new MenuConsultas();
        cadastrarConsulta = new PainelCadastrarConsulta();
        atualizarConsulta = new PainelAtualizarConsulta();
        removerConsulta = new PainelRemoverConsulta();
        PainelRelatorioConsulta relatorioConsulta = new PainelRelatorioConsulta();
        
        menu.setPainelPrincipal(this);
        cadastro.setPainelPrincipal(this);
        atualiza.setPainelPrincipal(this);
        remover.setPainelPrincipal(this);
        
        menuConsultas.setPainelPrincipal(this);
        cadastrarConsulta.setPainelPrincipal(this);
        atualizarConsulta.setPainelPrincipal(this);
        removerConsulta.setPainelPrincipal(this);
        relatorioConsulta.setPainelPrincipal(this);
        
        add(menu, "Menu");
        add(cadastro, "CadastroPaciente");
        add(atualiza, "atualziapaciente");
        add(remover, "removepaciente");
        
        add(menuConsultas, "MenuConsultas");
        add(cadastrarConsulta, "CadastrarConsulta");
        add(atualizarConsulta, "AtualizarConsulta");
        add(removerConsulta, "RemoverConsulta");
        add(relatorioConsulta, "GerarRelatorioConsulta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método main para teste do painel isoladamente.
     * Cria uma janela temporária para visualizar e testar o PainelSecretaria
     * sem precisar executar o sistema completo.
     * 
     * @param args argumentos de linha de comando (não utilizados)
     */
    public static void main(String[] args) {
        // Cria uma janela (JFrame) temporária só para segurar seu painel
        javax.swing.JFrame janelaTeste = new javax.swing.JFrame("Teste Rápido - Módulo Secretária");
        janelaTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        
        // Simula a ação de voltar (apenas imprime no console)
        java.awt.event.ActionListener acaoVoltarFake = e -> System.out.println("Clicou em Voltar (No sistema real, voltaria pro menu)");

        // Cria o SEU painel
        // OBS: Se o seu construtor não pede argumentos, tire o 'acaoVoltarFake' dos parênteses abaixo
        PainelSecretaria meuPainel = new PainelSecretaria(); 
        
        // Adiciona seu painel na janela de teste
        janelaTeste.add(meuPainel);
        janelaTeste.pack(); // Ajusta o tamanho
        janelaTeste.setSize(800, 600); // Força um tamanho bom
        janelaTeste.setLocationRelativeTo(null); // Centraliza
        janelaTeste.setVisible(true);
    }
    
    /**
     * Troca a tela exibida no painel principal.
     * Ao trocar para painéis de consulta, recarrega automaticamente a lista de pacientes
     * para garantir que pacientes recém-cadastrados estejam disponíveis.
     * 
     * @param nomeDaTela nome da tela a ser exibida (deve corresponder ao nome usado no add())
     */
    public void trocarTela(String nomeDaTela){
        // Recarrega a lista de pacientes quando trocar para painéis de consulta
        if (nomeDaTela.equals("CadastrarConsulta")) {
            cadastrarConsulta.recarregarPacientes();
        } else if (nomeDaTela.equals("AtualizarConsulta")) {
            atualizarConsulta.recarregarPacientes();
        } else if (nomeDaTela.equals("RemoverConsulta")) {
            removerConsulta.recarregarPacientes();
        }
        
        java.awt.CardLayout layout = (java.awt.CardLayout) this.getLayout();
        layout.show(this, nomeDaTela);
    }

}
