/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Secretaria;

import clinicaMedica.Paciente.CadastroPaciente;
import clinicaMedica.Paciente.AtualizaPaciente;
import clinicaMedica.Paciente.RemovePaciente;
import clinicaMedica.Menu;

/**
 *
 * @author Joaquim
 */
public class PainelSecretaria extends javax.swing.JPanel {

    /**
     * Creates new form PainelSecretaria
     */
    public PainelSecretaria() {
        initComponents();
        
        setLayout(new java.awt.CardLayout());
        
        CadastroPaciente cadastro = new CadastroPaciente();
        AtualizaPaciente atualiza = new AtualizaPaciente();
        RemovePaciente remover = new RemovePaciente();
        Menu menu = new Menu();
        
        menu.setPainelPrincipal(this);
        cadastro.setPainelPrincipal(this);
        atualiza.setPainelPrincipal(this);
        remover.setPainelPrincipal(this);
        
        add(menu, "Menu");
        add(cadastro, "CadastroPaciente");
        add(atualiza, "atualziapaciente");
        add(remover, "removepaciente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        // Cria uma janela (JFrame) temporária só para segurar seu painel
        javax.swing.JFrame janelaTeste = new javax.swing.JFrame("Teste Rápido - Módulo Secretária");
        janelaTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        
        // Simula a ação de voltar (apenas imprime no console)
        java.awt.event.ActionListener acaoVoltarFake = e -> System.out.println("Clicou em Voltar (No sistema real, voltaria pro menu)");

        // Cria o SEU painel
        // OBS: Se o seu construtor não pede argumentos, tire o 'acaoVoltarFake' dos parênteses abaixo
        PainelSecretaria meuPainel = new PainelSecretaria(); 
        
        // Adiciona seu painel na janela de teste
        janelaTeste.add(meuPainel);
        janelaTeste.pack(); // Ajusta o tamanho
        janelaTeste.setSize(800, 600); // Força um tamanho bom
        janelaTeste.setLocationRelativeTo(null); // Centraliza
        janelaTeste.setVisible(true);
    }
    
    // Metodo Publico que faz com que troque as telas, de forma generica.
    public void trocarTela(String nomeDaTela){
        java.awt.CardLayout layout = (java.awt.CardLayout) this.getLayout();
        layout.show(this, nomeDaTela);
    }

}
