/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaMedica.Medico;

import clinicaMedica.Paciente.AtualizarProntuario;
import clinicaMedica.Paciente.CadastrarProntuario;

/**
 * Painel principal do médico com navegação entre telas
 * @author Joaquim
 */
public class PainelMedico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelMedico.class.getName());

    /**
     * Creates new form PainelMedico
     */
    public PainelMedico() {
        initComponents();
        configurarPaineis();
    }
    
    /**
     * Configura os painéis do CardLayout
     */
    private void configurarPaineis() {
        setLayout(new java.awt.CardLayout());
        
        // Cria o menu principal do médico
        MenuMedicoPanel menuMedico = new MenuMedicoPanel();
        menuMedico.setPainelPrincipal(this);
        
        // Cria os painéis de gerenciamento
        CadastrarProntuario cadastrarProntuario = new CadastrarProntuario();
        AtualizarProntuario atualizarProntuario = new AtualizarProntuario();
        GerarRelatorios gerarRelatorios = new GerarRelatorios();
        
        // Configura os painéis principais
        cadastrarProntuario.setPainelPrincipal(this);
        atualizarProntuario.setPainelPrincipal(this);
        gerarRelatorios.setPainelPrincipal(this);
        
        // Adiciona ao CardLayout
        add(menuMedico, "Menu");
        add(cadastrarProntuario, "CadastrarProntuario");
        add(atualizarProntuario, "AtualizarProntuario");
        add(gerarRelatorios, "GerarRelatorios");
        
        // Mostra o menu inicialmente
        trocarTela("Menu");
    }

    /**
     * Método público que faz com que troque as telas, de forma genérica.
     * @param nomeDaTela nome da tela a ser exibida
     */
    public void trocarTela(String nomeDaTela) {
        java.awt.CardLayout layout = (java.awt.CardLayout) this.getContentPane().getLayout();
        layout.show(this.getContentPane(), nomeDaTela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Clínica Médica - Médico");
        setPreferredSize(new java.awt.Dimension(1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
