/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Paciente;

/**
 *
 * @author Joaquim
 */
public class AtualizarInfoAdd extends javax.swing.JPanel {

    /**
     * Creates new form AtualizarInfoAdd
     */
    public AtualizarInfoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obsAddtxt = new javax.swing.JLabel();
        doencaCardiacaBox = new javax.swing.JComboBox<>();
        cirurgiaBox = new javax.swing.JTextField();
        alergiaBox = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        obsAddBox = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        fumaBox = new javax.swing.JComboBox<>();
        cadastrarButton = new javax.swing.JButton();
        bebeBox = new javax.swing.JComboBox<>();
        colesterolBox = new javax.swing.JComboBox<>();
        cadastrartxt = new javax.swing.JLabel();
        cpfPacientetxt = new javax.swing.JLabel();
        fumatxt = new javax.swing.JLabel();
        bebetxt = new javax.swing.JLabel();
        colesteroltxt = new javax.swing.JLabel();
        diabetetxt = new javax.swing.JLabel();
        doençaCardiacatxt = new javax.swing.JLabel();
        cirurgiatxt = new javax.swing.JLabel();
        alergiatxt = new javax.swing.JLabel();
        diabeteBox = new javax.swing.JComboBox<>();
        obsAddtxt1 = new javax.swing.JLabel();

        obsAddtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        obsAddtxt.setText("Observações Adicionais");

        doencaCardiacaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doencaCardiacaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        cirurgiaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alergiaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        obsAddBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarButton.setText("Buscar");

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");

        fumaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fumaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarButton.setText("Atualizar");

        bebeBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bebeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        colesterolBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        colesterolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        cadastrartxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        cadastrartxt.setText("Atualizar Informações Adicionais");

        cpfPacientetxt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cpfPacientetxt.setText("CPF do Paciente");

        fumatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fumatxt.setText("Fuma");

        bebetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bebetxt.setText("Bebe");

        colesteroltxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        colesteroltxt.setText("Colesterol Alto");

        diabetetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diabetetxt.setText("Diabete");

        doençaCardiacatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doençaCardiacatxt.setText("Doença Cardíaca");

        cirurgiatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cirurgiatxt.setText("Cirurgias");

        alergiatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alergiatxt.setText("Alergias");

        diabeteBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diabeteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        obsAddtxt1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        obsAddtxt1.setText("Informações Médicas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(cadastrartxt))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(obsAddtxt1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(cpfPacientetxt)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(buscarButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(fumatxt)
                                                                        .addComponent(bebetxt)
                                                                        .addComponent(colesteroltxt)
                                                                        .addComponent(diabetetxt)
                                                                        .addComponent(doençaCardiacatxt)
                                                                        .addComponent(cirurgiatxt)
                                                                        .addComponent(alergiatxt))
                                                                .addGap(22, 22, 22)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(alergiatxt)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(doencaCardiacaBox, 0, 94, Short.MAX_VALUE)
                                                                                .addComponent(diabeteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(colesterolBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(bebeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(fumaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(obsAddtxt)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(cirurgiaBox)
                                                                        .addComponent(alergiaBox)
                                                                        .addComponent(obsAddBox, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(173, 173, 173)
                                                                .addComponent(cancelarButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cadastrarButton)))))
                                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cadastrartxt)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cpfPacientetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(obsAddtxt1)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(fumatxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bebetxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(colesteroltxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(diabetetxt)
                                                .addGap(18, 18, 18)
                                                .addComponent(doençaCardiacatxt)
                                                .addGap(18, 18, 18)
                                                .addComponent(cirurgiatxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(alergiatxt))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(fumaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bebeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(colesterolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addComponent(diabeteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(doencaCardiacaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cirurgiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(alergiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(obsAddBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(obsAddtxt))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelarButton)
                                        .addComponent(cadastrarButton))
                                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergiaBox;
    private javax.swing.JLabel alergiatxt;
    private javax.swing.JComboBox<String> bebeBox;
    private javax.swing.JLabel bebetxt;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cadastrartxt;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField cirurgiaBox;
    private javax.swing.JLabel cirurgiatxt;
    private javax.swing.JComboBox<String> colesterolBox;
    private javax.swing.JLabel colesteroltxt;
    private javax.swing.JLabel cpfPacientetxt;
    private javax.swing.JComboBox<String> diabeteBox;
    private javax.swing.JLabel diabetetxt;
    private javax.swing.JComboBox<String> doencaCardiacaBox;
    private javax.swing.JLabel doençaCardiacatxt;
    private javax.swing.JComboBox<String> fumaBox;
    private javax.swing.JLabel fumatxt;
    private javax.swing.JTextField obsAddBox;
    private javax.swing.JLabel obsAddtxt;
    private javax.swing.JLabel obsAddtxt1;
    // End of variables declaration//GEN-END:variables
}