/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Paciente;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import clinicaMedica.Secretaria.PainelSecretaria;

/**
 *
 * @author Joaquim
 */
public class AtualizaPaciente extends javax.swing.JPanel {

    private PainelSecretaria painelPrincipal;
    private Paciente pacienteEmEdicao = null;
    
    
    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
        
    }
    
    
    
    public AtualizaPaciente() {
        initComponents();
    }
    
    public void TelaAtualizar() {
        initComponents();
        // Carregue o Combo de Convênios igual na tela de cadastro
        tipoConvenioBox.setModel(new DefaultComboBoxModel<>(Paciente.tiposConvenios.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        editarInfotxt = new javax.swing.JLabel();
        cpfPaciente = new javax.swing.JLabel();
        novoNome = new javax.swing.JLabel();
        novoPlano = new javax.swing.JLabel();
        novoConvenio = new javax.swing.JLabel();
        novoEnderecoTitulo = new javax.swing.JLabel();
        novaRua = new javax.swing.JLabel();
        novoNumero = new javax.swing.JLabel();
        novoBairro = new javax.swing.JLabel();
        novoCidade = new javax.swing.JLabel();
        novoEstado = new javax.swing.JLabel();
        novoCEP = new javax.swing.JLabel();
        novoContatoTitulo = new javax.swing.JLabel();
        novoTelefone = new javax.swing.JLabel();
        novoCelular = new javax.swing.JLabel();
        novoEmail = new javax.swing.JLabel();
        dadosImportantesTitulo = new javax.swing.JLabel();
        campoNvCPF = new javax.swing.JTextField();
        campoNvNome = new javax.swing.JTextField();
        campoNvPlano = new javax.swing.JTextField();
        campoNvRua = new javax.swing.JTextField();
        campoNvNumero = new javax.swing.JTextField();
        campoNvBairro = new javax.swing.JTextField();
        campoNvCidade = new javax.swing.JTextField();
        campoNvEstado = new javax.swing.JTextField();
        campoNvCEP = new javax.swing.JTextField();
        campoNvTelefone = new javax.swing.JTextField();
        campoNvCelular = new javax.swing.JTextField();
        campoNvEmail = new javax.swing.JTextField();
        salvarAlteracoesButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        tipoConvenioBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(944, 557));
        setLayout(new java.awt.GridBagLayout());

        editarInfotxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        editarInfotxt.setText("EDITAR INFORMAÇÕES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        add(editarInfotxt, gridBagConstraints);

        cpfPaciente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cpfPaciente.setText("CPF do Paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(cpfPaciente, gridBagConstraints);

        novoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoNome.setText("Novo Nome: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 6, 0, 0);
        add(novoNome, gridBagConstraints);

        novoPlano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoPlano.setText("Novo Plano de Saúde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        add(novoPlano, gridBagConstraints);

        novoConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoConvenio.setText("Novo Convênio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoConvenio, gridBagConstraints);

        novoEnderecoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        novoEnderecoTitulo.setText("Novo Endereço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        add(novoEnderecoTitulo, gridBagConstraints);

        novaRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novaRua.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(novaRua, gridBagConstraints);

        novoNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoNumero.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoNumero, gridBagConstraints);

        novoBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoBairro.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoBairro, gridBagConstraints);

        novoCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCidade.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoCidade, gridBagConstraints);

        novoEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoEstado.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(novoEstado, gridBagConstraints);

        novoCEP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCEP.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        add(novoCEP, gridBagConstraints);

        novoContatoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        novoContatoTitulo.setText("Novo Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 21, 0, 0);
        add(novoContatoTitulo, gridBagConstraints);

        novoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoTelefone.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(novoTelefone, gridBagConstraints);

        novoCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCelular.setText("Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 21, 0, 0);
        add(novoCelular, gridBagConstraints);

        novoEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoEmail.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 0, 0);
        add(novoEmail, gridBagConstraints);

        dadosImportantesTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dadosImportantesTitulo.setText("Dados Importantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        add(dadosImportantesTitulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 56, 0, 0);
        add(campoNvCPF, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 56, 0, 0);
        add(campoNvNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 56, 0, 0);
        add(campoNvPlano, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 56, 0, 0);
        add(campoNvRua, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvNumero, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvBairro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvCidade, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 56, 0, 0);
        add(campoNvEstado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 56, 16, 0);
        add(campoNvCEP, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        add(campoNvTelefone, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 52, 0, 0);
        add(campoNvCelular, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 52, 0, 0);
        add(campoNvEmail, gridBagConstraints);

        salvarAlteracoesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvarAlteracoesButton.setText("Salvar Alterações");
        salvarAlteracoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlteracoesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 37, 0, 166);
        add(salvarAlteracoesButton, gridBagConstraints);

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 56, 0, 0);
        add(cancelarButton, gridBagConstraints);

        tipoConvenioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Plano de Saúde", " " }));
        tipoConvenioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoConvenioBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(tipoConvenioBox, gridBagConstraints);

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        add(buscarButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        painelPrincipal.trocarTela("Menu");
        limparCampos();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void tipoConvenioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoConvenioBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoConvenioBoxActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String cpf = campoNvCPF.getText().trim();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF para buscar.");
            return;
        }

        PacienteRepository repositorio = PacienteRepository.getInstancia();
        pacienteEmEdicao = repositorio.buscarPorCpf(cpf);

        if (pacienteEmEdicao == null) {
            JOptionPane.showMessageDialog(this, "Paciente não encontrado!");
            limparCampos();
            return;
        }

        // Preencha os campos com os dados do paciente
        campoNvNome.setText(pacienteEmEdicao.getNome());
        campoNvCPF.setText(pacienteEmEdicao.getCpf());
        campoNvCPF.setEditable(false);
        campoNvPlano.setText(pacienteEmEdicao.getPlano() == null ? "" : pacienteEmEdicao.getPlano());

        if (pacienteEmEdicao.getEndereco() != null) {
            campoNvRua.setText(pacienteEmEdicao.getEndereco().getRua());
            campoNvNumero.setText(pacienteEmEdicao.getEndereco().getNumero());
            campoNvBairro.setText(pacienteEmEdicao.getEndereco().getBairro());
            campoNvCidade.setText(pacienteEmEdicao.getEndereco().getCidade());
            campoNvEstado.setText(pacienteEmEdicao.getEndereco().getEstado());
            campoNvCEP.setText(pacienteEmEdicao.getEndereco().getCep());
        }

        // Contato
        if (pacienteEmEdicao.getContato() != null) {
            campoNvCelular.setText(pacienteEmEdicao.getContato().getCelular());
            campoNvTelefone.setText(pacienteEmEdicao.getContato().getTelefone());
            campoNvEmail.setText(pacienteEmEdicao.getContato().getEmail());
        }

        // Convênio (Selecionar o item certo no Combo)
        if (pacienteEmEdicao.getConvenio() != null) {
            tipoConvenioBox.setSelectedItem(pacienteEmEdicao.getConvenio());
        }
        



        
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void salvarAlteracoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAlteracoesButtonActionPerformed
        
        try {
            
            if (pacienteEmEdicao == null) {
            JOptionPane.showMessageDialog(this, "Busque um paciente primeiro antes de salvar!");
            return;
        }
        pacienteEmEdicao.setNome(campoNvNome.getText());
        
        if (pacienteEmEdicao.getEndereco() != null) {
            pacienteEmEdicao.getEndereco().setRua(campoNvRua.getText());
            pacienteEmEdicao.getEndereco().setNumero(campoNvNumero.getText());
            pacienteEmEdicao.getEndereco().setBairro(campoNvBairro.getText());
            pacienteEmEdicao.getEndereco().setCidade(campoNvCidade.getText());
            pacienteEmEdicao.getEndereco().setEstado(campoNvEstado.getText());
            pacienteEmEdicao.getEndereco().setCep(campoNvCEP.getText());
        }
        
        if (pacienteEmEdicao.getContato() != null) {
            pacienteEmEdicao.getContato().setCelular(campoNvCelular.getText());
            pacienteEmEdicao.getContato().setTelefone(campoNvTelefone.getText());
            pacienteEmEdicao.getContato().setEmail(campoNvEmail.getText());
        }
        
        pacienteEmEdicao.setConvenio((Paciente.tiposConvenios) tipoConvenioBox.getSelectedItem());
        PacienteRepository.getInstancia().atualizarPaciente(pacienteEmEdicao);
        JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
        limparCampos();
        pacienteEmEdicao = null;
        campoNvCPF.setEditable(true);
            
            
            
        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_salvarAlteracoesButtonActionPerformed
    
    private void limparCampos() {
        campoNvNome.setText("");
        campoNvCPF.setText("");
        campoNvPlano.setText("");
        campoNvRua.setText("");
        campoNvNumero.setText("");
        campoNvBairro.setText("");
        campoNvCidade.setText("");
        campoNvEstado.setText("");
        campoNvCEP.setText("");
        campoNvTelefone.setText("");
        campoNvCelular.setText("");
        campoNvEmail.setText("");
    
        if (tipoConvenioBox.getItemCount() > 0) tipoConvenioBox.setSelectedIndex(0);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField campoNvBairro;
    private javax.swing.JTextField campoNvCEP;
    private javax.swing.JTextField campoNvCPF;
    private javax.swing.JTextField campoNvCelular;
    private javax.swing.JTextField campoNvCidade;
    private javax.swing.JTextField campoNvEmail;
    private javax.swing.JTextField campoNvEstado;
    private javax.swing.JTextField campoNvNome;
    private javax.swing.JTextField campoNvNumero;
    private javax.swing.JTextField campoNvPlano;
    private javax.swing.JTextField campoNvRua;
    private javax.swing.JTextField campoNvTelefone;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfPaciente;
    private javax.swing.JLabel dadosImportantesTitulo;
    private javax.swing.JLabel editarInfotxt;
    private javax.swing.JLabel novaRua;
    private javax.swing.JLabel novoBairro;
    private javax.swing.JLabel novoCEP;
    private javax.swing.JLabel novoCelular;
    private javax.swing.JLabel novoCidade;
    private javax.swing.JLabel novoContatoTitulo;
    private javax.swing.JLabel novoConvenio;
    private javax.swing.JLabel novoEmail;
    private javax.swing.JLabel novoEnderecoTitulo;
    private javax.swing.JLabel novoEstado;
    private javax.swing.JLabel novoNome;
    private javax.swing.JLabel novoNumero;
    private javax.swing.JLabel novoPlano;
    private javax.swing.JLabel novoTelefone;
    private javax.swing.JButton salvarAlteracoesButton;
    private javax.swing.JComboBox<Object> tipoConvenioBox;
    // End of variables declaration//GEN-END:variables
}
