package clinicaMedica.Paciente;

// Imports necessários para a lógica de negócio e interface
import clinicaMedica.Paciente.Paciente;
import clinicaMedica.Paciente.PacienteRepository; // Assumindo esta classe como Singleton
import clinicaMedica.Paciente.InfoAdd;
import clinicaMedica.Medico.Prontuario;
import clinicaMedica.Medico.PainelMedico;
import clinicaMedica.Medico.RepositorioProntuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquim
 */
public class CadastrarProntuario extends javax.swing.JPanel {

    // Variáveis de controle
    // NOTE: Se for testar a classe diretamente com o 'main' abaixo, esta referência
    // será nula. Isso é normal, mas você não poderá usar o método 'trocarTela()'.
    private PainelMedico painelPrincipal;
    private Paciente pacienteEncontrado = null; // Armazena o paciente após a busca
    
    // Componente para exibir nome do paciente
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField campoNome;
    
    // Campos adicionais de saúde (InfoAdd)
    private javax.swing.JLabel labelDadosSaude;
    private javax.swing.JCheckBox checkFuma;
    private javax.swing.JCheckBox checkBebe;
    private javax.swing.JCheckBox checkColesterol;
    private javax.swing.JCheckBox checkDiabetes;
    private javax.swing.JCheckBox checkDoencaCardiaca;
    private javax.swing.JLabel labelCirurgias;
    private javax.swing.JTextField campoCirurgias;
    private javax.swing.JLabel labelAlergias;
    private javax.swing.JTextField campoAlergias;
    private javax.swing.JLabel labelObsAdicionais;
    private javax.swing.JTextField campoObsAdicionais;

    /**
     * Define a referência para o painel principal (Container).
     */
    public void setPainelPrincipal(PainelMedico p) {
        this.painelPrincipal = p;
    }

    /**
     * Creates new form CadastrarProntuario
     */
    public CadastrarProntuario() {
        initComponents();
    }


    /**
     * Limpa todos os campos do formulário.
     */
    private void limparCampos() {
        campoCpf.setText("");
        campoNome.setText("");
        campoSintomas.setText("");
        campoDiagnostico.setText("");
        campoPrescricao.setText("");
        
        // Limpar campos adicionais de saúde
        checkFuma.setSelected(false);
        checkBebe.setSelected(false);
        checkColesterol.setSelected(false);
        checkDiabetes.setSelected(false);
        checkDoencaCardiaca.setSelected(false);
        campoCirurgias.setText("");
        campoAlergias.setText("");
        campoObsAdicionais.setText("");
        
        pacienteEncontrado = null;
        campoCpf.setEditable(true);
        campoCpf.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarProntuarioTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        sintomasTXt = new javax.swing.JLabel();
        diagnosticosTxt = new javax.swing.JLabel();
        prescricaoTxt = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoSintomas = new javax.swing.JTextField();
        campoDiagnostico = new javax.swing.JTextField();
        campoPrescricao = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        cadastrarProntuarioButton = new javax.swing.JButton();

        cadastrarProntuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastrarProntuarioTxt.setText("Cadastrar Prontuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cpf do Paciente");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNome.setText("Nome do Paciente");

        sintomasTXt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sintomasTXt.setText("Sintomas");

        diagnosticosTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diagnosticosTxt.setText("Diagnosticos");

        prescricaoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prescricaoTxt.setText("Prescrição");

        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNome.setEditable(false);
        campoNome.setBackground(new java.awt.Color(240, 240, 240));

        campoSintomas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoPrescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoPrescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrescricaoActionPerformed(evt);
            }
        });

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        cadastrarProntuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrarProntuarioButton.setText("Cadastrar");
        cadastrarProntuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProntuarioButtonActionPerformed(evt);
            }
        });

        // Inicializar componentes InfoAdd
        labelDadosSaude = new javax.swing.JLabel();
        labelDadosSaude.setFont(new java.awt.Font("Segoe UI", 1, 14));
        labelDadosSaude.setText("Dados Adicionais de Saúde:");
        
        checkFuma = new javax.swing.JCheckBox();
        checkFuma.setText("Fuma");
        
        checkBebe = new javax.swing.JCheckBox();
        checkBebe.setText("Bebe");
        
        checkColesterol = new javax.swing.JCheckBox();
        checkColesterol.setText("Colesterol Alto");
        
        checkDiabetes = new javax.swing.JCheckBox();
        checkDiabetes.setText("Diabetes");
        
        checkDoencaCardiaca = new javax.swing.JCheckBox();
        checkDoencaCardiaca.setText("Doença Cardíaca");
        
        labelCirurgias = new javax.swing.JLabel();
        labelCirurgias.setText("Cirurgias:");
        
        campoCirurgias = new javax.swing.JTextField();
        
        labelAlergias = new javax.swing.JLabel();
        labelAlergias.setText("Alergias:");
        
        campoAlergias = new javax.swing.JTextField();
        
        labelObsAdicionais = new javax.swing.JLabel();
        labelObsAdicionais.setText("Observações:");
        
        campoObsAdicionais = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(382, 382, 382)
                                                .addComponent(cadastrarProntuarioTxt))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(labelNome)
                                                                        .addComponent(sintomasTXt)
                                                                        .addComponent(diagnosticosTxt)
                                                                        .addComponent(prescricaoTxt)
                                                                        .addComponent(labelDadosSaude)
                                                                        .addComponent(labelCirurgias)
                                                                        .addComponent(labelAlergias)
                                                                        .addComponent(labelObsAdicionais))
                                                                .addGap(64, 64, 64)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(campoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                                                        .addComponent(campoNome)
                                                                        .addComponent(campoSintomas)
                                                                        .addComponent(campoDiagnostico)
                                                                        .addComponent(campoPrescricao)
                                                                        .addComponent(campoCirurgias)
                                                                        .addComponent(campoAlergias)
                                                                        .addComponent(campoObsAdicionais)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(checkFuma)
                                                                                .addGap(20, 20, 20)
                                                                                .addComponent(checkBebe)
                                                                                .addGap(20, 20, 20)
                                                                                .addComponent(checkColesterol))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(checkDiabetes)
                                                                                .addGap(20, 20, 20)
                                                                                .addComponent(checkDoencaCardiaca))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(349, 349, 349)
                                                                .addComponent(cancelarButton)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addComponent(cadastrarProntuarioButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addComponent(buscarButton)))))
                                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cadastrarProntuarioTxt)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscarButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNome)
                                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sintomasTXt)
                                        .addComponent(campoSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diagnosticosTxt)
                                        .addComponent(campoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(prescricaoTxt)
                                        .addComponent(campoPrescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelDadosSaude)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkFuma)
                                        .addComponent(checkBebe)
                                        .addComponent(checkColesterol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkDiabetes)
                                        .addComponent(checkDoencaCardiaca))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCirurgias)
                                        .addComponent(campoCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelAlergias)
                                        .addComponent(campoAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelObsAdicionais)
                                        .addComponent(campoObsAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelarButton)
                                        .addComponent(cadastrarProntuarioButton))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // Ação opcional: Chamar a busca ao pressionar Enter no campo CPF
        buscarButtonActionPerformed(evt);
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoPrescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrescricaoActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String cpf = campoCpf.getText().trim();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF para buscar o paciente.");
            return;
        }

        try {
            // 1. Busca do Paciente no Repositório (Presumindo um Singleton)
            PacienteRepository repositorio = PacienteRepository.getInstancia();
            pacienteEncontrado = repositorio.buscarPorCpf(cpf);

            if (pacienteEncontrado == null) {
                JOptionPane.showMessageDialog(this, "Paciente não encontrado.");
                return;
            }

            // 2. Carregar dados adicionais de saúde se existirem
            InfoAdd infoAdd = pacienteEncontrado.getInfoAdd();
            if (infoAdd != null) {
                checkFuma.setSelected(infoAdd.getFuma());
                checkBebe.setSelected(infoAdd.getBebe());
                checkColesterol.setSelected(infoAdd.isColesterol());
                checkDiabetes.setSelected(infoAdd.isDiabetes());
                checkDoencaCardiaca.setSelected(infoAdd.isDoencaCardiaca());
                campoCirurgias.setText(infoAdd.getCirurgias() != null ? infoAdd.getCirurgias() : "");
                campoAlergias.setText(infoAdd.getAlergia() != null ? infoAdd.getAlergia() : "");
                campoObsAdicionais.setText(infoAdd.getObsAdicionais() != null ? infoAdd.getObsAdicionais() : "");
            }

            // 3. Exibir nome do paciente
            campoNome.setText(pacienteEncontrado.getNome());
            
            // 4. Informações de sucesso
            JOptionPane.showMessageDialog(this, "Paciente encontrado: " + pacienteEncontrado.getNome());
            campoCpf.setEditable(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar paciente: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Lógica para o botão Cadastrar.
     * Cria e adiciona um novo Prontuário ao paciente encontrado.
     */
    private void cadastrarProntuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (pacienteEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Primeiro, busque um paciente!");
            return;
        }

        // 1. Captura e validação dos dados
        String sintomas = campoSintomas.getText().trim();
        String diagnostico = campoDiagnostico.getText().trim();
        String prescricao = campoPrescricao.getText().trim();

        if (sintomas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Sintomas' é obrigatório.");
            return;
        }

        if (diagnostico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Diagnóstico' é obrigatório.");
            return;
        }

        try {
            // 2. Cria o novo prontuário
            Prontuario novoProntuario = new Prontuario(
                sintomas, 
                diagnostico, 
                prescricao.isEmpty() ? "Nenhuma" : prescricao,
                pacienteEncontrado
            );

            // 3. Salva o prontuário diretamente no repositório
            // Evita problemas de lazy initialization
            RepositorioProntuario.getInstancia().cadastraProntuario(novoProntuario);

            // 4. Salva ou atualiza os dados adicionais de saúde (InfoAdd)
            InfoAdd infoAdd = pacienteEncontrado.getInfoAdd();
            if (infoAdd == null) {
                infoAdd = new InfoAdd();
                pacienteEncontrado.setInfoAdd(infoAdd);
            }
            
            // Atualiza os valores do InfoAdd com os dados dos campos
            infoAdd.setFuma(checkFuma.isSelected());
            infoAdd.setBebe(checkBebe.isSelected());
            infoAdd.setColesterol(checkColesterol.isSelected());
            infoAdd.setDiabetes(checkDiabetes.isSelected());
            infoAdd.setDoencaCardiaca(checkDoencaCardiaca.isSelected());
            infoAdd.setCirurgias(campoCirurgias.getText().trim().isEmpty() ? null : campoCirurgias.getText().trim());
            infoAdd.setAlergia(campoAlergias.getText().trim().isEmpty() ? null : campoAlergias.getText().trim());
            infoAdd.setObsAdicionais(campoObsAdicionais.getText().trim().isEmpty() ? null : campoObsAdicionais.getText().trim());
            
            // Salva as alterações no paciente (incluindo InfoAdd)
            PacienteRepository.getInstancia().atualizarPaciente(pacienteEncontrado);

            JOptionPane.showMessageDialog(this, "Prontuário e dados de saúde cadastrados com sucesso para o paciente " + pacienteEncontrado.getNome());

            // 5. Limpa e prepara para o próximo cadastro
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar prontuário: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Lógica para o botão Cancelar.
     * Limpa os campos e volta para a tela principal (Menu do Médico).
     */
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        limparCampos();
        // Ação para voltar ao menu principal
        if (painelPrincipal != null) {
            painelPrincipal.trocarTela("Menu");
        } else {
            JOptionPane.showMessageDialog(this, "Operação cancelada. Limpando campos.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cadastrarProntuarioButton;
    private javax.swing.JLabel cadastrarProntuarioTxt;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoDiagnostico;
    private javax.swing.JTextField campoPrescricao;
    private javax.swing.JTextField campoSintomas;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel diagnosticosTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel prescricaoTxt;
    private javax.swing.JLabel sintomasTXt;
    // End of variables declaration//GEN-END:variables
}