/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.View;

/**
 *
 * @author Joaquim
 */
public class Menu extends javax.swing.JPanel {

    
    private PainelSecretaria painelPrincipal;
    
    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
    }
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuTxt = new javax.swing.JLabel();
        cadastrarPaciente = new javax.swing.JButton();
        removerPaciente = new javax.swing.JButton();
        atualizarPaciente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(944, 557));
        setLayout(new java.awt.GridBagLayout());

        menuTxt.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        menuTxt.setText("MENU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 418, 0, 0);
        add(menuTxt, gridBagConstraints);

        cadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadastrarPaciente.setText("Cadastrar Paciente");
        cadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(83, 377, 0, 341);
        add(cadastrarPaciente, gridBagConstraints);

        removerPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        removerPaciente.setText("Remover Paciente");
        removerPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(83, 377, 0, 0);
        add(removerPaciente, gridBagConstraints);

        atualizarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        atualizarPaciente.setText("Atualizar Paciente");
        atualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 377, 124, 0);
        add(atualizarPaciente, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void removerPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPacienteActionPerformed
        painelPrincipal.trocarTela("removepaciente");
    }//GEN-LAST:event_removerPacienteActionPerformed
     
    private void cadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacienteActionPerformed
        painelPrincipal.trocarTela("CadastroPaciente");
    }//GEN-LAST:event_cadastrarPacienteActionPerformed

    
    
    private void atualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPacienteActionPerformed
        painelPrincipal.trocarTela("atualziapaciente");
        
    }//GEN-LAST:event_atualizarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarPaciente;
    private javax.swing.JButton cadastrarPaciente;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JButton removerPaciente;
    // End of variables declaration//GEN-END:variables
}
