/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Paciente;

/**
 *
 * @author Joaquim
 */
public class RemoverProntuario extends javax.swing.JPanel {

    /**
     * Creates new form RemoverProntuario
     */
    public RemoverProntuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removerProntuarioTxt = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        removerProntuarioButton = new javax.swing.JButton();

        removerProntuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removerProntuarioTxt.setText("Remover Prontuario");

        cpfTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpfTxt.setText("Cpf do Paciente");

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarButton.setText("Cancelar");

        removerProntuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removerProntuarioButton.setText("Remover Prontuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(removerProntuarioTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(cpfTxt)
                        .addGap(49, 49, 49)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removerProntuarioButton)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(removerProntuarioTxt)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTxt)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerProntuarioButton)
                    .addComponent(cancelarButton))
                .addContainerGap(411, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCpf;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfTxt;
    private javax.swing.JButton removerProntuarioButton;
    private javax.swing.JLabel removerProntuarioTxt;
    // End of variables declaration//GEN-END:variables
}
