/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Paciente;

import clinicaMedica.Paciente.Paciente;
import clinicaMedica.Paciente.PacienteRepository;
import clinicaMedica.Secretaria.PainelSecretaria;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquim
 */
public class RemovePaciente extends javax.swing.JPanel {

    private PainelSecretaria painelPrincipal;

    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
    }

    public RemovePaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        removerPacientetxt = new javax.swing.JLabel();
        cpfPaciente = new javax.swing.JLabel();
        campoCpfPaciente = new javax.swing.JTextField();
        removerButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        removerPacientetxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        removerPacientetxt.setText("REMOVER PACIENTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 316, 0, 0);
        add(removerPacientetxt, gridBagConstraints);

        cpfPaciente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cpfPaciente.setText("CPF do Paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 247, 0, 0);
        add(cpfPaciente, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 46, 0, 0);
        add(campoCpfPaciente, gridBagConstraints);

        removerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removerButton.setText("Efetuar Remoção");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 27, 366, 290);
        add(removerButton, gridBagConstraints);

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 273, 366, 0);
        add(cancelarButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento acionado ao clicar no botão Cancelar.
     * Limpa os campos e retorna à tela principal do menu.
     * 
     * @param evt evento de ação do botão
     */
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed

        // Verifica se o container principal existe antes de tentar trocar a tela
        if (painelPrincipal != null) {
            // 1. Retorna para a tela principal (Menu)
            painelPrincipal.trocarTela("Menu");
        } else {
            // Se o painelPrincipal não estiver configurado, exibe um aviso (opcional)
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: O Painel Principal (PainelSecretaria) não foi configurado corretamente.");
        }

        // 2. Limpa o campo de CPF
        campoCpfPaciente.setText("");
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * Evento acionado ao clicar no botão Efetuar Remoção.
     * Valida o CPF informado, busca o paciente no repositório,
     * solicita confirmação e remove o paciente do banco de dados.
     * 
     * @param evt evento de ação do botão
     */
    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String cpf = campoCpfPaciente.getText().trim();
        
        // Valida se o CPF foi informado
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, informe o CPF do paciente.", 
                "Campo Obrigatório", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            PacienteRepository repository = new PacienteRepository();
            Paciente paciente = repository.buscarPorCpf(cpf);
            
            if (paciente == null) {
                JOptionPane.showMessageDialog(this, 
                    "Paciente com CPF " + cpf + " não encontrado.", 
                    "Paciente Não Encontrado", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Confirma a remoção
            int opcao = JOptionPane.showConfirmDialog(this, 
                "Deseja realmente remover o paciente " + paciente.getNome() + "?", 
                "Confirmar Remoção", 
                JOptionPane.YES_NO_OPTION);
            
            if (opcao == JOptionPane.YES_OPTION) {
                repository.removerPaciente(cpf);
                
                JOptionPane.showMessageDialog(this, 
                    "Paciente removido com sucesso!", 
                    "Sucesso", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Limpa o campo
                campoCpfPaciente.setText("");
                
                // Retorna ao menu
                if (painelPrincipal != null) {
                    painelPrincipal.trocarTela("Menu");
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao remover paciente: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCpfPaciente;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfPaciente;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel removerPacientetxt;
    // End of variables declaration//GEN-END:variables
}
