/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Consulta;

import clinicaMedica.Secretaria.PainelSecretaria;

/**
 *
 * @author User
 */
public class MenuConsultas extends javax.swing.JPanel {

    private PainelSecretaria painelPrincipal;
    
    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
    }
    
    /**
     * Creates new form MenuConsultas
     */
    public MenuConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuTxt = new javax.swing.JLabel();
        cadastrarConsulta = new javax.swing.JButton();
        atualizarConsulta = new javax.swing.JButton();
        removerConsulta = new javax.swing.JButton();
        gerarRelatorio = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(944, 557));
        setLayout(new java.awt.GridBagLayout());

        menuTxt.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        menuTxt.setText("Gerenciar Consultas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(menuTxt, gridBagConstraints);

        cadastrarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadastrarConsulta.setText("Cadastrar Consulta");
        cadastrarConsulta.setPreferredSize(new java.awt.Dimension(280, 50));
        cadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        add(cadastrarConsulta, gridBagConstraints);

        atualizarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        atualizarConsulta.setText("Atualizar Consulta");
        atualizarConsulta.setPreferredSize(new java.awt.Dimension(280, 50));
        atualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(atualizarConsulta, gridBagConstraints);

        removerConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        removerConsulta.setText("Remover Consulta");
        removerConsulta.setPreferredSize(new java.awt.Dimension(280, 50));
        removerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(removerConsulta, gridBagConstraints);

        gerarRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gerarRelatorio.setText("Gerar Relatórios");
        gerarRelatorio.setPreferredSize(new java.awt.Dimension(280, 50));
        gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(gerarRelatorio, gridBagConstraints);

        voltarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.setPreferredSize(new java.awt.Dimension(150, 40));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        add(voltarButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConsultaActionPerformed
        painelPrincipal.trocarTela("CadastrarConsulta");
    }//GEN-LAST:event_cadastrarConsultaActionPerformed

    private void atualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarConsultaActionPerformed
        painelPrincipal.trocarTela("AtualizarConsulta");
    }//GEN-LAST:event_atualizarConsultaActionPerformed

    private void removerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerConsultaActionPerformed
        painelPrincipal.trocarTela("RemoverConsulta");
    }//GEN-LAST:event_removerConsultaActionPerformed

    private void gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorioActionPerformed
        painelPrincipal.trocarTela("GerarRelatorioConsulta");
    }//GEN-LAST:event_gerarRelatorioActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        painelPrincipal.trocarTela("Menu");
    }//GEN-LAST:event_voltarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarConsulta;
    private javax.swing.JButton cadastrarConsulta;
    private javax.swing.JButton gerarRelatorio;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JButton removerConsulta;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
