/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.Consulta;

import clinicaMedica.Secretaria.PainelSecretaria;
import clinicaMedica.Paciente.Paciente;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PainelCadastrarConsulta extends javax.swing.JPanel {

    private PainelSecretaria painelPrincipal;
    
    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
    }
    
    /**
     * Creates new form PainelCadastrarConsulta
     */
    public PainelCadastrarConsulta() {
        initComponents();
        carregarCombos();
    }
    
    private void carregarCombos() {
        javax.persistence.EntityManager em =
            javax.persistence.Persistence
                .createEntityManagerFactory("ConsultorioPU")
                .createEntityManager();

        // Carregar pacientes
        java.util.List<Paciente> listaPacientes =
                em.createQuery("FROM Paciente", Paciente.class).getResultList();
        for (Paciente p : listaPacientes) {
            comboPaciente.addItem(p);
        }
        
        comboPaciente.setSelectedIndex(-1);

        em.close();
    }
    
    public void recarregarPacientes() {
        comboPaciente.removeAllItems();
        carregarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        campoData = new javax.swing.JTextField();
        campoHorario = new javax.swing.JTextField();
        radioNormal = new javax.swing.JRadioButton();
        radioRetorno = new javax.swing.JRadioButton();
        comboPaciente = new javax.swing.JComboBox<>();
        voltarButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastrar Consulta");

        jLabel2.setText("Data:");

        jLabel3.setText("Horário:");

        jLabel5.setText("Paciente:");

        jLabel6.setText("Tipo de consulta:");

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        campoData.setText("dd/mm/aaaa");
        campoData.setToolTipText("");

        campoHorario.setText("HH:mm");

        buttonGroup1.add(radioNormal);
        radioNormal.setText("Normal (1 hora)");

        buttonGroup1.add(radioRetorno);
        radioRetorno.setText("Retorno (30 min)");

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(radioNormal)
                        .addGap(7, 7, 7)
                        .addComponent(radioRetorno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioNormal)
                    .addComponent(radioRetorno))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        String textoData = campoData.getText();
        String textoHora = campoHorario.getText();
        
        Paciente paciente = (Paciente) comboPaciente.getSelectedItem();

        boolean normal = radioNormal.isSelected();
        boolean retorno = radioRetorno.isSelected();
            
        if (textoData.isEmpty() || textoData.equals("dd/mm/aaaa")) {
            JOptionPane.showMessageDialog(this, "Informe a data");
            return;
        }
        
        if (textoHora.isEmpty() || textoHora.equals("HH:mm")) {
            JOptionPane.showMessageDialog(this, "Informe a hora");
            return;
        }
        
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente");
            return;
        }
        
        if (!normal && !retorno) {
            JOptionPane.showMessageDialog(this, "Selecione o tipo da consulta");
            return;
        }
        
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data;
        try {
            data = LocalDate.parse(textoData, df);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data inválida. Use o formato dd/mm/aaaa");
            return;
        }
        
        DateTimeFormatter hf = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime hora;
        try {
            hora = LocalTime.parse(textoHora, hf);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Horário inválido. Use o formato HH:mm");
            return;
        }
        
        Consulta.typo tipo;
        if (radioNormal.isSelected()) {
            tipo = Consulta.typo.NORMAL;
        } else {
            tipo = Consulta.typo.RETORNO;
        }
        
        LocalDateTime dataHora = data.atTime(hora);
        
        Consulta consulta;
        consulta = new Consulta(dataHora, dataHora, paciente, tipo);
                
        new ConsultaService().cadastrar(consulta);
        JOptionPane.showMessageDialog(this, "Consulta cadastrada com sucesso!");
        
        limparCampos();
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        painelPrincipal.trocarTela("MenuConsultas");
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void limparCampos() {
        campoData.setText("dd/mm/aaaa");
        campoHorario.setText("HH:mm");
        buttonGroup1.clearSelection();
        comboPaciente.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoHorario;
    private javax.swing.JComboBox<Paciente> comboPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioRetorno;
    private javax.swing.JButton salvarButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
