/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaMedica.Consulta;


import clinicaMedica.Medico.Doutor;
import clinicaMedica.Paciente.Paciente;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */

public class TelaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastrar() {
        initComponents();
        carregarCombos();
    }
    
    private void carregarCombos() {
    javax.persistence.EntityManager em =
        javax.persistence.Persistence
            .createEntityManagerFactory("clinica-medicaPU")
            .createEntityManager();

    // Carregar pacientes
    java.util.List<Paciente> listaPacientes =
            em.createQuery("FROM Paciente", Paciente.class).getResultList();
    for (Paciente p : listaPacientes) {
        jComboBox1.addItem(p);
    }

    // Carregar médicos
    java.util.List<Doutor> listaMedicos =
            em.createQuery("FROM Doutor", Doutor.class).getResultList();
    for (Doutor d : listaMedicos) {
        jComboBox2.addItem(d);
    }

    em.close();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Consulta");

        jLabel2.setText("Data:");

        jLabel3.setText("Horario:");

        jLabel4.setText("Médico:");

        jLabel5.setText("Paciente:");

        jLabel6.setText("Tipo de consulta:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("dd/mm/aaaa");
        jTextField1.setToolTipText("");

        jTextField2.setText("digite um horario");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Normal");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Retorno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(jRadioButton1)
                .addGap(7, 7, 7)
                .addComponent(jRadioButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String textoData = jTextField1.getText();
    String textoHora = jTextField2.getText();
    
    Paciente paciente = (Paciente) jComboBox1.getSelectedItem();
    Doutor medico = (Doutor) jComboBox2.getSelectedItem();

    boolean normal = jRadioButton1.isSelected();
    boolean retorno = jRadioButton2.isSelected();
    // chamar lógica do sistema (sem banco por enquanto)
        
        if (textoData.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a data");
            return;
        }
        
        if (textoHora.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a hora");
            return;
        }
        
        if (medico == null) {
            JOptionPane.showMessageDialog(this, "Selecione um medico");
            return;
        }
        
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente");
            return;
        }
        
        if (!normal && !retorno) {
            JOptionPane.showMessageDialog(this, "Selecione o tipo da consulta");
            return;
        }
        
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data;
        try {
            data = LocalDate.parse(textoData, df);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data inválida");
            return;
        }
        
        DateTimeFormatter hf = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime hora;
        try {
            hora = LocalTime.parse(textoHora, hf);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Horário inválido");
        return;
        }
        
        Consulta.TipoConsulta tipo;
        if (jRadioButton1.isSelected()) {
            tipo = Consulta.TipoConsulta.NORMAL;
        }   
        else {
            tipo = Consulta.TipoConsulta.RETORNO;
        }
        
        Consulta consulta;
        consulta = new Consulta(data, hora, medico, paciente, tipo);
                
        new ConsultaService().cadastrar(consulta);
        JOptionPane.showMessageDialog(this, "Paciente cadastrado com sucesso!");
        this.dispose(); 
        //new TelaOpcoes().setVisible(true); // volta pra tela principal
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Paciente> jComboBox1;
    private javax.swing.JComboBox<Doutor> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
