/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaMedica.Consulta;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaOpcaoConsultas extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultas
     */
    
    private enum OpcaoConsulta {
        CADASTRAR, ATUALIZAR, REMOVER, RELATORIO
    }
    
    private OpcaoConsulta opcaoSelecionada;
    
    public TelaOpcaoConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Cadastrar");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, java.awt.BorderLayout.LINE_END);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Atualizar");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Remover");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, java.awt.BorderLayout.LINE_START);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Gerenciar relatórios de consulta");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        opcaoSelecionada = OpcaoConsulta.ATUALIZAR;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (opcaoSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma opção");
            return;
        }
        
        switch (opcaoSelecionada){
            case CADASTRAR:
                new TelaCadastrar().setVisible(true);
                break;
            case ATUALIZAR:
                new TelaAtualizar().setVisible(true);
                break;
            case REMOVER:
                new TelaRemover().setVisible(true);
                break;
            case RELATORIO:
                new TelaGerenciarRelatorio().setVisible(true);
                break;
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        opcaoSelecionada = OpcaoConsulta.RELATORIO;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        opcaoSelecionada = OpcaoConsulta.REMOVER;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        opcaoSelecionada = OpcaoConsulta.CADASTRAR;
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    
public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new TelaOpcaoConsultas().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
