/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaMedica.Consulta;

import clinicaMedica.Medico.Doutor;
import clinicaMedica.Paciente.Paciente;
import java.awt.CardLayout;

/**
 *
 * @author User
 */
public class TelaAtualizar extends javax.swing.JFrame {

    private PanelSelecionarPaciente tela1;
    private PanelSelecionarConsulta tela2;
    private PanelEditarConsulta tela3;

    public TelaAtualizar() {
        initComponents();  // cria o containerPanel
        initCards();       // adiciona seus painéis ao CardLayout
    }
    
    
    public void mostrarTela(String nome) {
        CardLayout cl = (CardLayout) containerPanel.getLayout();
        cl.show(containerPanel, nome);
    }
    
    public PanelSelecionarPaciente getTela1() { return tela1; }
    public PanelSelecionarConsulta getTela2() { return tela2; }
    public PanelEditarConsulta getTela3() { return tela3; }

    private void initCards() {
        // instanciar paineis
        tela1 = new PanelSelecionarPaciente(this);
        tela2 = new PanelSelecionarConsulta(this);
        tela3 = new PanelEditarConsulta(this);

        // aplicar cardlayout no container
        CardLayout cl = new CardLayout();
        containerPanel.setLayout(cl);

        // adicionar as telas
        containerPanel.add(tela1, "selecionarPaciente");
        containerPanel.add(tela2, "selecionarConsulta");
        containerPanel.add(tela3, "editarConsulta");
        mostrarTela("selecionarPaciente");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    // End of variables declaration//GEN-END:variables
}
