package clinicaMedica.View;

import javax.swing.JOptionPane;
// ATENÇÃO: Se essas classes abaixo ficarem vermelhas, é porque você ainda não criou elas.
// Veja o passo 2 da minha resposta para criá-las.
import clinicaMedica.Model.Prontuario.Prontuario;
import clinicaMedica.Model.Prontuario.ProntuarioRepository;

/**
 *
 * @author Joaquim
 */
public class AtualizarProntuario extends javax.swing.JPanel {

    /**
     * Creates new form AtualizarProntuario
     */
    public AtualizarProntuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        novoDiagnosticosTxt = new javax.swing.JLabel();
        novaPrescricaoTxt = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        campoSintomas = new javax.swing.JTextField();
        campoDiagnostico = new javax.swing.JTextField();
        campoPrescricao = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        cadastrarProntuarioTxt = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cadastrarProntuarioButton = new javax.swing.JButton();
        novoSintomasTXt = new javax.swing.JLabel();

        novoDiagnosticosTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoDiagnosticosTxt.setText("Novo Diagnostico");

        novaPrescricaoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novaPrescricaoTxt.setText("Nova Prescrição");

        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        campoSintomas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoPrescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoPrescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrescricaoActionPerformed(evt);
            }
        });

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        cadastrarProntuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastrarProntuarioTxt.setText("Atualizar Prontuario");

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cpf do Paciente");

        cadastrarProntuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrarProntuarioButton.setText("Atualizar");
        cadastrarProntuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProntuarioButtonActionPerformed(evt);
            }
        });

        novoSintomasTXt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoSintomasTXt.setText("Novo Sintoma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(382, 382, 382)
                                                .addComponent(cadastrarProntuarioTxt))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(novoSintomasTXt)
                                                                        .addComponent(novoDiagnosticosTxt)
                                                                        .addComponent(novaPrescricaoTxt))
                                                                .addGap(64, 64, 64)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(campoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                                        .addComponent(campoSintomas)
                                                                        .addComponent(campoDiagnostico)
                                                                        .addComponent(campoPrescricao)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(349, 349, 349)
                                                                .addComponent(cancelarButton)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addComponent(cadastrarProntuarioButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addComponent(buscarButton)))))
                                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cadastrarProntuarioTxt)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscarButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(novoSintomasTXt)
                                        .addComponent(campoSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(novoDiagnosticosTxt)
                                        .addComponent(campoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(novaPrescricaoTxt)
                                        .addComponent(campoPrescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelarButton)
                                        .addComponent(cadastrarProntuarioButton))
                                .addContainerGap(300, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void campoPrescricaoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // --- LÓGICA DO BOTÃO ATUALIZAR ---
    private void cadastrarProntuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String cpf = campoCpf.getText();
        String sintomas = campoSintomas.getText();
        String diagnostico = campoDiagnostico.getText();
        String prescricao = campoPrescricao.getText();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O CPF é obrigatório para atualizar.");
            return;
        }

        // Cria o objeto com os dados da tela
        Prontuario p = new Prontuario();
        p.setCpfPaciente(cpf);
        p.setSintomas(sintomas);
        p.setDiagnostico(diagnostico);
        p.setPrescricao(prescricao);

        // Chama o repositório para salvar (atualizar)
        ProntuarioRepository repo = ProntuarioRepository.getInstancia();
        repo.atualizar(p);

        JOptionPane.showMessageDialog(this, "Prontuário atualizado com sucesso!");
        limparCampos();
    }

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        limparCampos();
    }

    private void limparCampos() {
        campoCpf.setText("");
        campoSintomas.setText("");
        campoDiagnostico.setText("");
        campoPrescricao.setText("");
        campoCpf.requestFocus();
    }

    // --- LÓGICA DO BOTÃO BUSCAR ---
    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String cpf = campoCpf.getText();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o CPF.");
            return;
        }

        // Chama o repositório para buscar
        ProntuarioRepository repo = ProntuarioRepository.getInstancia();
        Prontuario p = repo.buscarPorCpf(cpf);

        if (p != null) {
            campoSintomas.setText(p.getSintomas());
            campoDiagnostico.setText(p.getDiagnostico());
            campoPrescricao.setText(p.getPrescricao());
        } else {
            JOptionPane.showMessageDialog(this, "Prontuário não encontrado para este CPF!");
            limparCampos();
        }
    }

    // --- MÉTODO MAIN (Para rodar a tela sozinha e testar) ---
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AtualizarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame("Teste Atualizar Prontuário");
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                frame.add(new AtualizarProntuario());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cadastrarProntuarioButton;
    private javax.swing.JLabel cadastrarProntuarioTxt;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoDiagnostico;
    private javax.swing.JTextField campoPrescricao;
    private javax.swing.JTextField campoSintomas;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel novaPrescricaoTxt;
    private javax.swing.JLabel novoDiagnosticosTxt;
    private javax.swing.JLabel novoSintomasTXt;
    // End of variables declaration                   
}