package clinicaMedica.View;

import clinicaMedica.Model.Paciente.Paciente;
import clinicaMedica.Model.Paciente.PacienteRepository;
import clinicaMedica.Model.Paciente.Endereco; 
import clinicaMedica.Model.Paciente.Contato;  
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Joaquim
 */
public class AtualizaPaciente extends javax.swing.JPanel {

    private PainelSecretaria painelPrincipal;
    private Paciente pacienteEmEdicao = null;


    public void setPainelPrincipal(PainelSecretaria p){
        this.painelPrincipal = p;
    }


    public AtualizaPaciente() {
        initComponents();
    }

    public void TelaAtualizar() {
        // Inicializa o ComboBox de Convênios
        tipoConvenioBox.setModel(new DefaultComboBoxModel<>(Paciente.tiposConvenios.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        editarInfotxt = new javax.swing.JLabel();
        cpfPaciente = new javax.swing.JLabel();
        novoNome = new javax.swing.JLabel();
        novoPlano = new javax.swing.JLabel();
        novoConvenio = new javax.swing.JLabel();
        novoEnderecoTitulo = new javax.swing.JLabel();
        novaRua = new javax.swing.JLabel();
        novoNumero = new javax.swing.JLabel();
        novoBairro = new javax.swing.JLabel();
        novoCidade = new javax.swing.JLabel();
        novoEstado = new javax.swing.JLabel();
        novoCEP = new javax.swing.JLabel();
        novoContatoTitulo = new javax.swing.JLabel();
        novoTelefone = new javax.swing.JLabel();
        novoCelular = new javax.swing.JLabel();
        novoEmail = new javax.swing.JLabel();
        dadosImportantesTitulo = new javax.swing.JLabel();
        campoNvCPF = new javax.swing.JTextField();
        campoNvNome = new javax.swing.JTextField();
        campoNvPlano = new javax.swing.JTextField();
        campoNvRua = new javax.swing.JTextField();
        campoNvNumero = new javax.swing.JTextField();
        campoNvBairro = new javax.swing.JTextField();
        campoNvCidade = new javax.swing.JTextField();
        campoNvEstado = new javax.swing.JTextField();
        campoNvCEP = new javax.swing.JTextField();
        campoNvTelefone = new javax.swing.JTextField();
        campoNvCelular = new javax.swing.JTextField();
        campoNvEmail = new javax.swing.JTextField();
        salvarAlteracoesButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        tipoConvenioBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(944, 557));
        setLayout(new java.awt.GridBagLayout());

        editarInfotxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        editarInfotxt.setText("EDITAR INFORMAÇÕES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        add(editarInfotxt, gridBagConstraints);

        cpfPaciente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cpfPaciente.setText("CPF do Paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(cpfPaciente, gridBagConstraints);

        novoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoNome.setText("Novo Nome: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 6, 0, 0);
        add(novoNome, gridBagConstraints);

        novoPlano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoPlano.setText("Novo Plano de Saúde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        add(novoPlano, gridBagConstraints);

        novoConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoConvenio.setText("Novo Convênio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoConvenio, gridBagConstraints);

        novoEnderecoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        novoEnderecoTitulo.setText("Novo Endereço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        add(novoEnderecoTitulo, gridBagConstraints);

        novaRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novaRua.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(novaRua, gridBagConstraints);

        novoNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoNumero.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoNumero, gridBagConstraints);

        novoBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoBairro.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoBairro, gridBagConstraints);

        novoCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCidade.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(novoCidade, gridBagConstraints);

        novoEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoEstado.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(novoEstado, gridBagConstraints);

        novoCEP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCEP.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        add(novoCEP, gridBagConstraints);

        novoContatoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        novoContatoTitulo.setText("Novo Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 21, 0, 0);
        add(novoContatoTitulo, gridBagConstraints);

        novoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoTelefone.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(novoTelefone, gridBagConstraints);

        novoCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoCelular.setText("Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 21, 0, 0);
        add(novoCelular, gridBagConstraints);

        novoEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        novoEmail.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 0, 0);
        add(novoEmail, gridBagConstraints);

        dadosImportantesTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dadosImportantesTitulo.setText("Dados Importantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        add(dadosImportantesTitulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 56, 0, 0);
        add(campoNvCPF, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 56, 0, 0);
        add(campoNvNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 56, 0, 0);
        add(campoNvPlano, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 56, 0, 0);
        add(campoNvRua, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvNumero, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvBairro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(campoNvCidade, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 56, 0, 0);
        add(campoNvEstado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 56, 16, 0);
        add(campoNvCEP, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        add(campoNvTelefone, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 52, 0, 0);
        add(campoNvCelular, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 52, 0, 0);
        add(campoNvEmail, gridBagConstraints);

        salvarAlteracoesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvarAlteracoesButton.setText("Salvar Alterações");
        salvarAlteracoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlteracoesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 37, 0, 166);
        add(salvarAlteracoesButton, gridBagConstraints);

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 56, 0, 0);
        add(cancelarButton, gridBagConstraints);

        tipoConvenioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Plano de Saúde", " " }));
        tipoConvenioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoConvenioBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 56, 0, 0);
        add(tipoConvenioBox, gridBagConstraints);

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        add(buscarButton, gridBagConstraints);
    }// </editor-fold>

    /**
     * Lógica para o botão Cancelar.
     * Volta para o painel principal e limpa os campos.
     */
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (painelPrincipal != null) {
            painelPrincipal.trocarTela("Menu");
        } else {
             // Caso esteja rodando no método main, apenas fecha a janela
             JOptionPane.showMessageDialog(this, "Operação cancelada. Limpando campos.");
        }
        limparCampos();
    }

    private void tipoConvenioBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // Nada a fazer aqui por enquanto
    }

    /**
     * Lógica para o botão Buscar.
     * Busca o paciente pelo CPF e preenche os campos do formulário com seus dados.
     */
    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {

        String cpf = campoNvCPF.getText();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF para buscar.");
            return;
        }

        PacienteRepository repositorio;
        try {
            // 1. Acesso ao Repositório (Pode falhar se o Repositório não estiver configurado)
            repositorio = PacienteRepository.getInstancia();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erro ao acessar o repositório de pacientes: " + e.getMessage());
             return;
        }

        // 2. Busca do Paciente
        pacienteEmEdicao = repositorio.buscarPorCpf(cpf);

        if (pacienteEmEdicao == null) {
            JOptionPane.showMessageDialog(this, "Paciente não encontrado para o CPF: " + cpf);
            limparCampos();
            return;
        }
        
        // --- Preenchimento dos Campos ---
        
        campoNvNome.setText(pacienteEmEdicao.getNome());
        campoNvCPF.setEditable(false); // Impede a edição do CPF após a busca
        
        // 3. Preenchimento do Endereço (Checa se o objeto Endereco não é nulo)
        Endereco endereco = pacienteEmEdicao.getEndereco();
        if (endereco != null) {
            // Checa se os atributos dentro do Endereco não são nulos também (máxima segurança)
            campoNvRua.setText(endereco.getRua() != null ? endereco.getRua() : "");
            campoNvNumero.setText(endereco.getNumero() != null ? endereco.getNumero() : "");
            campoNvBairro.setText(endereco.getBairro() != null ? endereco.getBairro() : "");
            campoNvCidade.setText(endereco.getCidade() != null ? endereco.getCidade() : "");
            campoNvEstado.setText(endereco.getEstado() != null ? endereco.getEstado() : "");
            campoNvCEP.setText(endereco.getCep() != null ? endereco.getCep() : "");
        } else {
             // Garante que campos de endereço ficam vazios se não houver Endereco
             campoNvRua.setText("");
             campoNvNumero.setText("");
             campoNvBairro.setText("");
             campoNvCidade.setText("");
             campoNvEstado.setText("");
             campoNvCEP.setText("");
        }

        // 4. Preenchimento do Contato (Checa se o objeto Contato não é nulo)
        Contato contato = pacienteEmEdicao.getContato();
        if (contato != null) {
            // Checa se os atributos dentro do Contato não são nulos
            campoNvCelular.setText(contato.getCelular() != null ? contato.getCelular() : "");
            campoNvTelefone.setText(contato.getTelefone() != null ? contato.getTelefone() : "");
            campoNvEmail.setText(contato.getEmail() != null ? contato.getEmail() : "");
        } else {
             // Garante que campos de contato ficam vazios se não houver Contato
             campoNvCelular.setText("");
             campoNvTelefone.setText("");
             campoNvEmail.setText("");
        }

        // 5. Preenchimento do Convênio
        if (pacienteEmEdicao.getConvenio() != null) {
            tipoConvenioBox.setSelectedItem(pacienteEmEdicao.getConvenio());
        } else {
            if (tipoConvenioBox.getItemCount() > 0) tipoConvenioBox.setSelectedIndex(0);
        }
        
        JOptionPane.showMessageDialog(this, "Paciente " + pacienteEmEdicao.getNome() + " carregado para edição.");
    }

    /**
     * Lógica para o botão Salvar Alterações.
     * Atualiza o objeto pacienteEmEdicao com os novos dados e salva no repositório.
     */
    private void salvarAlteracoesButtonActionPerformed(java.awt.event.ActionEvent evt) {

        try {

            if (pacienteEmEdicao == null) {
                JOptionPane.showMessageDialog(this, "Busque um paciente primeiro antes de salvar!");
                return;
            }
            
            // 1. Atualiza Dados Importantes
            pacienteEmEdicao.setNome(campoNvNome.getText());
            // **LOGICA DO PLANO DE SAUDE REMOVIDA AQUI**
            // pacienteEmEdicao.setPlanoDeSaude(campoNvPlano.getText()); 

            // 2. Atualiza Endereço
            Endereco endereco = pacienteEmEdicao.getEndereco();
            if (endereco == null) {
                // Se o Endereço for null, cria uma nova instância
                endereco = new Endereco();
                pacienteEmEdicao.setEndereco(endereco);
            }
            endereco.setRua(campoNvRua.getText());
            endereco.setNumero(campoNvNumero.getText());
            endereco.setBairro(campoNvBairro.getText());
            endereco.setCidade(campoNvCidade.getText());
            endereco.setEstado(campoNvEstado.getText());
            endereco.setCep(campoNvCEP.getText());
            

            // 3. Atualiza Contato
            Contato contato = pacienteEmEdicao.getContato();
            if (contato == null) {
                // Se o Contato for null, cria uma nova instância
                contato = new Contato();
                pacienteEmEdicao.setContato(contato);
            }
            contato.setCelular(campoNvCelular.getText());
            contato.setTelefone(campoNvTelefone.getText());
            contato.setEmail(campoNvEmail.getText());
            

            // 4. Atualiza Convênio
            pacienteEmEdicao.setConvenio((Paciente.tiposConvenios) tipoConvenioBox.getSelectedItem());
            
            // 5. Salva no Repositório
            PacienteRepository.getInstancia().atualizarPaciente(pacienteEmEdicao);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            
            // 6. Finaliza a Edição
            limparCampos();
            pacienteEmEdicao = null;
            campoNvCPF.setEditable(true);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void limparCampos() {
        campoNvNome.setText("");
        campoNvCPF.setText("");
        // **LOGICA DO PLANO DE SAUDE REMOVIDA AQUI**
        // campoNvPlano.setText(""); 
        
        campoNvRua.setText("");
        campoNvNumero.setText("");
        campoNvBairro.setText("");
        campoNvCidade.setText("");
        campoNvEstado.setText("");
        campoNvCEP.setText("");
        campoNvTelefone.setText("");
        campoNvCelular.setText("");
        campoNvEmail.setText("");

        if (tipoConvenioBox.getItemCount() > 0) tipoConvenioBox.setSelectedIndex(0);
        campoNvCPF.setEditable(true);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField campoNvBairro;
    private javax.swing.JTextField campoNvCEP;
    private javax.swing.JTextField campoNvCPF;
    private javax.swing.JTextField campoNvCelular;
    private javax.swing.JTextField campoNvCidade;
    private javax.swing.JTextField campoNvEmail;
    private javax.swing.JTextField campoNvEstado;
    private javax.swing.JTextField campoNvNome;
    private javax.swing.JTextField campoNvNumero;
    private javax.swing.JTextField campoNvPlano;
    private javax.swing.JTextField campoNvRua;
    private javax.swing.JTextField campoNvTelefone;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfPaciente;
    private javax.swing.JLabel dadosImportantesTitulo;
    private javax.swing.JLabel editarInfotxt;
    private javax.swing.JLabel novaRua;
    private javax.swing.JLabel novoBairro;
    private javax.swing.JLabel novoCEP;
    private javax.swing.JLabel novoCelular;
    private javax.swing.JLabel novoCidade;
    private javax.swing.JLabel novoContatoTitulo;
    private javax.swing.JLabel novoConvenio;
    private javax.swing.JLabel novoEmail;
    private javax.swing.JLabel novoEnderecoTitulo;
    private javax.swing.JLabel novoEstado;
    private javax.swing.JLabel novoNome;
    private javax.swing.JLabel novoNumero;
    private javax.swing.JLabel novoPlano;
    private javax.swing.JLabel novoTelefone;
    private javax.swing.JButton salvarAlteracoesButton;
    private javax.swing.JComboBox<Object> tipoConvenioBox;
    // End of variables declaration

    // Método main para teste (mantido da resposta anterior)
    public static void main(String args[]) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Atualizar Paciente (Modo Teste)");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                AtualizaPaciente panel = new AtualizaPaciente();
                panel.TelaAtualizar(); 
                frame.getContentPane().add(panel);
                frame.pack();
                frame.setLocationRelativeTo(null); 
                frame.setVisible(true);
            }
        });
    }
}