/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.View;

/**
 *
 * @author Joaquim
 */
public class CadastrarInfoAdd extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarInfoAdd
     */
    public CadastrarInfoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrartxt = new javax.swing.JLabel();
        cpfPacientetxt = new javax.swing.JLabel();
        fumatxt = new javax.swing.JLabel();
        bebetxt = new javax.swing.JLabel();
        colesteroltxt = new javax.swing.JLabel();
        diabetetxt = new javax.swing.JLabel();
        doençaCardiacatxt = new javax.swing.JLabel();
        cirurgiatxt = new javax.swing.JLabel();
        alergiatxt = new javax.swing.JLabel();
        obsAddtxt = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        fumaBox = new javax.swing.JComboBox<>();
        bebeBox = new javax.swing.JComboBox<>();
        colesterolBox = new javax.swing.JComboBox<>();
        diabeteBox = new javax.swing.JComboBox<>();
        doencaCardiacaBox = new javax.swing.JComboBox<>();
        cirurgiaBox = new javax.swing.JTextField();
        alergiaBox = new javax.swing.JTextField();
        obsAddBox = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();

        cadastrartxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastrartxt.setText("Cadastrar Informações Adicionais");

        cpfPacientetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpfPacientetxt.setText("Cpf do Paciente");

        fumatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fumatxt.setText("Paciente Fuma ?");

        bebetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bebetxt.setText("Paciente Bebe ?");

        colesteroltxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        colesteroltxt.setText("Paciente tem colesterol alto ?");

        diabetetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diabetetxt.setText("Paciente tem Diabete?");

        doençaCardiacatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doençaCardiacatxt.setText("Paciente tem doença cardiaca ?");

        cirurgiatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cirurgiatxt.setText("Cirurgias");

        alergiatxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alergiatxt.setText("Alergias");

        obsAddtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        obsAddtxt.setText("Obs Adicionais");

        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        fumaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fumaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        bebeBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bebeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não", " " }));

        colesterolBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        colesterolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        diabeteBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diabeteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        doencaCardiacaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doencaCardiacaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sim", "não" }));

        cirurgiaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alergiaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        obsAddBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buscarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarButton.setText("Buscar");

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");

        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarButton.setText("Cadastrar Informações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(cadastrartxt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfPacientetxt)
                                    .addComponent(fumatxt)
                                    .addComponent(bebetxt)
                                    .addComponent(colesteroltxt)
                                    .addComponent(diabetetxt))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoCpf)
                                    .addComponent(fumaBox, 0, 198, Short.MAX_VALUE)
                                    .addComponent(bebeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(colesterolBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diabeteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doençaCardiacatxt)
                                    .addComponent(cirurgiatxt)
                                    .addComponent(alergiatxt)
                                    .addComponent(obsAddtxt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doencaCardiacaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cirurgiaBox)
                                    .addComponent(alergiaBox)
                                    .addComponent(obsAddBox))))
                        .addGap(95, 95, 95)
                        .addComponent(buscarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cadastrarButton)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastrartxt)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfPacientetxt)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fumatxt)
                    .addComponent(fumaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bebetxt)
                    .addComponent(bebeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colesteroltxt)
                    .addComponent(colesterolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diabetetxt)
                    .addComponent(diabeteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doençaCardiacatxt)
                    .addComponent(doencaCardiacaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirurgiatxt)
                    .addComponent(cirurgiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alergiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarButton)
                            .addComponent(cancelarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alergiatxt)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obsAddtxt)
                            .addComponent(obsAddBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergiaBox;
    private javax.swing.JLabel alergiatxt;
    private javax.swing.JComboBox<String> bebeBox;
    private javax.swing.JLabel bebetxt;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cadastrartxt;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField cirurgiaBox;
    private javax.swing.JLabel cirurgiatxt;
    private javax.swing.JComboBox<String> colesterolBox;
    private javax.swing.JLabel colesteroltxt;
    private javax.swing.JLabel cpfPacientetxt;
    private javax.swing.JComboBox<String> diabeteBox;
    private javax.swing.JLabel diabetetxt;
    private javax.swing.JComboBox<String> doencaCardiacaBox;
    private javax.swing.JLabel doençaCardiacatxt;
    private javax.swing.JComboBox<String> fumaBox;
    private javax.swing.JLabel fumatxt;
    private javax.swing.JTextField obsAddBox;
    private javax.swing.JLabel obsAddtxt;
    // End of variables declaration//GEN-END:variables
}
