/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clinicaMedica.View;

/**
 *
 * @author Joaquim
 */
public class RemoverInfoAdd extends javax.swing.JPanel {

    /**
     * Creates new form RemoverInfoAdd
     */
    public RemoverInfoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarProntuarioTxt = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        removerProntuarioButton = new javax.swing.JButton();

        cadastrarProntuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastrarProntuarioTxt.setText("Remover Informações Adicionais");

        cpfTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpfTxt.setText("Cpf do Paciente");

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarButton.setText("Cancelar");

        removerProntuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removerProntuarioButton.setText("Remover Informações Adicionais");
        removerProntuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProntuarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cpfTxt)
                                .addGap(49, 49, 49)
                                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadastrarProntuarioTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removerProntuarioButton)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cadastrarProntuarioTxt)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTxt)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerProntuarioButton)
                    .addComponent(cancelarButton))
                .addContainerGap(426, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed

    private void removerProntuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProntuarioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerProntuarioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrarProntuarioTxt;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cpfTxt;
    private javax.swing.JButton removerProntuarioButton;
    // End of variables declaration//GEN-END:variables
}
